name: EC2 Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LAB branch
        uses: actions/checkout@v3
        with:
          ref: lab

      - name: Run deployment script on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}      
          username: ${{ secrets.EC2_USER }}    
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            chmod +x resources/deploy_ec2.sh
            ./resources/deploy_ec2.sh